### ISSUE TITLE
Does this work with aggregate?

### ISSUE THREAD

**Issue by pizzarob** [baldercm/mongoose-bignumber#4]
I would expect this to work, but does not. Does this library support aggregate pipelines? If not do you know what it would take to get working? 

```js
   // This finds a document
    const found = await BnSchema.find({
       num: {
         $lte: 126,
       },
     }).exec();


   // This finds no documents
    const foundWithAggregate = await BnSchema.aggregate([
      {
        $match: {
          num: {
            $lte: 126,
          },
        },
      },
    ]).exec();

```

**Comment by pizzarob** [comment]
Maybe not? Found this about aggregate in the mongoose docs:

>The documents returned are plain javascript objects, not mongoose documents (since any shape of document can be returned).

**Comment by baldercm** [comment]
Hey @pizzarob

As far a as I known, Mongoose does not perform any cast/conversion for aggregate stages.

On the other hand, keep in mind that BigNumberSchema values will be stored as Strings on MongoDB. The exact same cast/conversion will be applied both when saving your models and running queries (rounding, scale and conversion to String).

If you turn on Mongoose's debugging with `mongoose.set('debug', true)` you can check the actual queries that are being run.

Your document in MongoDB will be similar to:
`{_id: xxxx, num: '126'}` (note the quote Strings)

Your first query will be converted to something like:
`bnschemas.findOne({ num: '126' }, { fields: {} })` (note the quote Strings)

But the aggregate will be something like:
`bnschemas.aggregate([ { '$match': { num: 126 } } ], {})` (note the absence of quote Strings, so no documents match the criteria)

Hope this helps.

**Comment by pizzarob** [comment]
Thanks @baldercm. I ended up changing all my BN types to strings. I was dependent on queries with $lte and $gte and in order to get them to work properly with aggregation I am using [collation](https://docs.mongodb.com/manual/reference/collation/) and setting numericOrdering to true. Queries will then properly compare numbers represented as strings.
